---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loklok
  labels:
    app: loklok
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: loklok
  template:
    metadata:
      labels:
        app: loklok
    spec:
      containers:
        - name: loklok
          image: docker.io/phengbunath/loklok:2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080